:concurrency: 3
:timeout: 60
:verbose: true
:queues:
  - default

:scheduler:
  :schedule:
    supplier_data_job:
      cron: '0 */6 * * *'
      class: SupplierDataJob
    hotel_data_cleaner_job:
      cron: '*/30 * * * *'
      class: HotelDataCleanerJob
